import abc from "../../assets/Images/abc4.jpg";
import abc5 from "../../assets/Images/abc6.jpg";
import abc10 from "../../assets/Images/mhadev.avif";
import abc3 from "../../assets/Images/abc9.jpg";
import abc2 from "../../assets/Images/abc2.jpg";

export const BigsamplePackages = [
  {
    id: 1,
    name: "Varanasi Spiritual Tour",
    duration: "3 Days / 2 Nights",
    price: 4999,
    location: "Varanasi",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Arrival & Ganga Aarti",
      "Day 2: Kashi Vishwanath Temple Visit",
      "Day 3: Sarnath & Departure",
    ],
    image: abc,
  },
  {
    id: 2,
    name: "Ayodhya Ram Janmabhoomi Tour",
    duration: "2 Days / 1 Night",
    price: 3999,
    location: "Varanasi",
    services: ["Transport", "Accommodation", "Guide"],
    itinerary: [
      "Day 1: Ram Janmabhoomi Temple Visit",
      "Day 2: Hanuman Garhi & Local Sightseeing",
    ],
    image: abc2,
  },
  {
    id: 3,
    name: "Mathura-Vrindavan Pilgrimage",
    duration: "4 Days / 3 Nights",
    price: 5999,
    image: abc5,
    location: "Mathura & Vrindavan",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    description:
      "Experience the spiritual essence of Varanasi with guided temple visits, Ganga Aarti, and boat rides. Perfect for those seeking peace and cultural exploration.",
    itinerary: [
      "Day 1: Krishna Janmabhoomi Temple",
      "Day 2: Banke Bihari Temple & Prem Mandir",
      "Day 3: ISKCON Temple & Local Markets",
      "Day 4: Departure",
    ],
  },
  {
    id: 4,
    name: "Prayagraj Sangam & Kumbh Experience",
    duration: "3 Days / 2 Nights",
    price: 5499,
    location: "Prayagraj",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Sangam Snan & Hanuman Mandir",
      "Day 2: Anand Bhawan & Kumbh Mela Visit",
      "Day 3: Departure",
    ],
    image: abc10,
  },
  {
    id: 5,
    name: "Haridwar-Rishikesh Ganga Tour",
    duration: "5 Days / 4 Nights",
    price: 7499,
    location: "Varanasi",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Har Ki Pauri Ganga Aarti",
      "Day 2: Mansa Devi & Chandi Devi Temple",
      "Day 3: Rishikesh Ram Jhula & Laxman Jhula",
      "Day 4: Yoga & Adventure Activities",
      "Day 5: Departure",
    ],
    image: abc3,
  },
  {
    id: 6,
    name: "Varanasi Spiritual Tour",
    duration: "3 Days / 2 Nights",
    price: 4500,
    location: "Varanasi, Uttar Pradesh",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Ganga Aarti at Dashashwamedh Ghat",
      "Day 2: Kashi Vishwanath Temple & Sarnath",
      "Day 3: Morning Boat Ride & Departure",
    ],
    image: abc,
  },
  {
    id: 7,
    name: "Ayodhya Ram Mandir Tour",
    duration: "2 Days / 1 Night",
    price: 3500,
    location: "Ayodhya, Uttar Pradesh",
    services: ["Transport", "Accommodation", "Guide"],
    itinerary: [
      "Day 1: Shri Ram Janmabhoomi Temple",
      "Day 1 Evening: Saryu Aarti",
      "Day 2: Hanuman Garhi & Kanak Bhawan",
    ],
    image: abc2,
  },
  {
    id: 8,
    name: "Mathura-Vrindavan Pilgrimage",
    duration: "3 Days / 2 Nights",
    price: 4999,
    location: "Mathura, Uttar Pradesh",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Krishna Janmabhoomi Temple",
      "Day 2: Banke Bihari Temple & Prem Mandir",
      "Day 3: Govardhan Parikrama & Departure",
    ],
    image: abc3,
  },
  {
    id: 9,
    name: "Prayagraj Sangam & Kumbh Visit",
    duration: "2 Days / 1 Night",
    price: 3999,
    location: "Prayagraj, Uttar Pradesh",
    services: ["Transport", "Accommodation", "Guide"],
    itinerary: [
      "Day 1: Triveni Sangam Snan & Hanuman Mandir",
      "Day 2: Akshayvat Tree & Anand Bhawan",
    ],
    image: abc,
  },
  {
    id: 12,
    name: "Haridwar-Rishikesh Ganga Tour",
    duration: "5 Days / 4 Nights",
    price: 7499,
    location: "Haridwar & Rishikesh, Uttarakhand",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Har Ki Pauri Ganga Aarti",
      "Day 2: Mansa Devi & Chandi Devi Temple",
      "Day 3: Rishikesh Ram Jhula & Laxman Jhula",
      "Day 4: Yoga & Adventure Activities",
      "Day 5: Departure",
    ],
    image: abc5,
  },
  {
    id: 106,
    name: "Kedarnath Yatra",
    duration: "6 Days / 5 Nights",
    price: 12999,
    location: "Kedarnath, Uttarakhand",
    services: ["Transport", "Accommodation", "Food", "Guide", "Pony Service"],
    itinerary: [
      "Day 1: Haridwar Arrival",
      "Day 2: Guptkashi Stay",
      "Day 3: Kedarnath Trek & Darshan",
      "Day 4: Kedarnath Temple Morning Aarti",
      "Day 5: Return to Guptkashi",
      "Day 6: Departure",
    ],
    image: abc3,
  },
  {
    id: 721,
    name: "Badrinath Yatra",
    duration: "5 Days / 4 Nights",
    price: 11999,
    location: "Badrinath, Uttarakhand",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Haridwar Arrival",
      "Day 2: Joshimath Stay",
      "Day 3: Badrinath Darshan",
      "Day 4: Mana Village Visit",
      "Day 5: Departure",
    ],
    image: abc2,
  },
  {
    id: 823,
    name: "Dwarka-Somnath Tour",
    duration: "4 Days / 3 Nights",
    price: 8999,
    location: "Dwarka & Somnath, Gujarat",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Dwarkadhish Temple",
      "Day 2: Nageshwar Jyotirlinga",
      "Day 3: Somnath Temple",
      "Day 4: Departure",
    ],
    image: abc5,
  },
];

