import abc from "../../assets/Images/abc4.jpg";
import abc5 from "../../assets/Images/abc6.jpg";
import abc10 from "../../assets/Images/mhadev.avif";
import abc3 from "../../assets/Images/abc9.jpg";
import abc2 from "../../assets/Images/abc2.jpg";

export const HolyPlacespackage = [
  {
    id: 1,
    name: "Varanasi (Kashi, Banaras)",
    duration: "3 Days / 2 Nights",
    price: 4999,
    catagory: "Holy",
    description:
      " Known as the spiritual capital of India, Varanasi is one of the world’s oldest continuously inhabited cities. The Kashi Vishwanath Temple dedicated to Lord Shiva is the most important shrine here. The evening Ganga Aarti at Dashashwamedh Ghat is a divine spectacle. Visitors can also take boat rides on the Ganga River, explore ancient ghats, and witness centuries-old traditions",
    location: "Varanasi",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Arrival & Ganga Aarti",
      "Day 2: Kashi Vishwanath Temple Visit",
      "Day 3: Sarnath & Departure",
    ],
    image: abc,
  },
  {
    id: 2,
    name: "Ayodhya Ram Janmabhoomi Tour",
    duration: "2 Days / 1 Night",
    price: 3999,
   catagory: "Holy",
    location: "Varanasi",
    description:
      "Famed as the birthplace of Lord Rama, Ayodhya holds immense religious significance. The recently built Ram Mandir attracts millions of devotees worldwide. Other attractions include Hanuman Garhi, Kanak Bhawan, and the serene banks of the Sarayu River. The city is rich in Ramayana heritage and cultural legacy.",
    services: ["Transport", "Accommodation", "Guide"],
    itinerary: [
      "Day 1: Ram Janmabhoomi Temple Visit",
      "Day 2: Hanuman Garhi & Local Sightseeing",
    ],
    image: abc2,
  },
  {
    id: 3,
    name: "Mathura-Vrindavan ",
    catagory: "Holy",
    duration: "4 Days / 3 Nights",
    price: 5999,
    image: abc5,
    location: "Mathura & Vrindavan",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    description:
      "Mathura, the birthplace of Lord Krishna, and Vrindavan, where he spent his childhood, are centers of devotion. Famous temples include Dwarkadhish Temple, ISKCON Temple, Banke Bihari Temple, and Prem Mandir. Festivals like Janmashtami and Holi are celebrated with great grandeur.",
    itinerary: [
      "Day 1: Krishna Janmabhoomi Temple",
      "Day 2: Banke Bihari Temple & Prem Mandir",
      "Day 3: ISKCON Temple & Local Markets",
      "Day 4: Departure",
    ],
  },
  {
    id: 4,
    name: "Prayagraj Sangam & Kumbh Experience",
    duration: "3 Days / 2 Nights",
    catagory: "Holy",
    price: 5499,
    location: "Prayagraj",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Sangam Snan & Hanuman Mandir",
      "Day 2: Anand Bhawan & Kumbh Mela Visit",
      "Day 3: Departure",
    ],
    image: abc10,
  },
  {
    id: 5,
    name: "Prayagraj (Allahabad): ",
    duration: "5 Days / 4 Nights",
    catagory: "Holy",
    price: 7499,
    location: "Varanasi",
    description:
      "A city of confluence, Prayagraj is home to Triveni Sangam, where rivers Ganga, Yamuna, and Saraswati meet. It hosts the world’s largest religious gathering – Kumbh Mela. The Akshayavat Tree and Anand Bhawan add historical and cultural depth to this holy city.",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Har Ki Pauri Ganga Aarti",
      "Day 2: Mansa Devi & Chandi Devi Temple",
      "Day 3: Rishikesh Ram Jhula & Laxman Jhula",
      "Day 4: Yoga & Adventure Activities",
      "Day 5: Departure",
    ],
    image: abc3,
  },
  {
    id: 6,
    name: "Prayagraj (Allahabad): ",
    duration: "5 Days / 4 Nights",
    price: 7499,
    location: "Varanasi",
    catagory: "Holy",
    description:
      "A city of confluence, Prayagraj is home to Triveni Sangam, where rivers Ganga, Yamuna, and Saraswati meet. It hosts the world’s largest religious gathering – Kumbh Mela. The Akshayavat Tree and Anand Bhawan add historical and cultural depth to this holy city.",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Har Ki Pauri Ganga Aarti",
      "Day 2: Mansa Devi & Chandi Devi Temple",
      "Day 3: Rishikesh Ram Jhula & Laxman Jhula",
      "Day 4: Yoga & Adventure Activities",
      "Day 5: Departure",
    ],
    image: abc,
  },
  {
    id: 7,
    name: "Chitrakoot",
    duration: "2 Days / 1 Night",
    price: 3500,
    catagory: "Holy",
    location: "Ayodhya, Uttar Pradesh",
    description:
      "Deeply connected with Lord Rama’s exile, Chitrakoot is a land of religious significance and natural beauty. Key sites include Ramghat, Kamadgiri, Bharat Milap Temple, Hanuman Dhara, and Sati Anusuya Ashram. The serene surroundings make it a peaceful pilgrimage destination.",
    services: ["Transport", "Accommodation", "Guide"],
    itinerary: [
      "Day 1: Shri Ram Janmabhoomi Temple",
      "Day 1 Evening: Saryu Aarti",
      "Day 2: Hanuman Garhi & Kanak Bhawan",
    ],
    image: abc2,
  },
  {
    id: 8,
    name: "Vindhyachal (Mirzapur)",
    duration: "3 Days / 2 Nights",
    price: 4999,
    catagory: "Holy",
    location: "Mathura, Uttar Pradesh",
    description:
      "Vindhyachal is one of the most powerful Shakti Peeths, dedicated to Goddess Vindhyavasini. The temple is located on the banks of the Ganga River and attracts lakhs of devotees. Nearby attractions include Sita Kund, Ashtabhuja Temple, and Kalikhoh Temple.",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Krishna Janmabhoomi Temple",
      "Day 2: Banke Bihari Temple & Prem Mandir",
      "Day 3: Govardhan Parikrama & Departure",
    ],
    image: abc3,
  },
  {
    id: 9,
    name: "Sarnath (Varanasi) ",
    duration: "2 Days / 1 Night",
    price: 3999,
    catagory: "Holy",
    location: "Prayagraj, Uttar Pradesh",
    description:
      "A sacred Buddhist site where Lord Buddha delivered his first sermon after attaining enlightenment. Key attractions include Dhamek Stupa, Chaukhandi Stupa, Ashoka Pillar, and the Sarnath Museum. It is a center of peace, meditation, and Buddhist heritage.",
    services: ["Transport", "Accommodation", "Guide"],
    itinerary: [
      "Day 1: Triveni Sangam Snan & Hanuman Mandir",
      "Day 2: Akshayvat Tree & Anand Bhawan",
    ],
    image: abc,
  },
  {
    id: 12,
    name: "Gorakhpur",
    duration: "5 Days / 4 Nights",
    price: 7499,
    catagory: "Holy",
    location: "Haridwar & Rishikesh, Uttarakhand",
    description:
      "Famous for Gorakhnath Temple dedicated to Guru Gorakhnath, the city is an important religious hub. Ramgarh Tal Lake and Geeta Press, which publishes Hindu religious texts, are also notable sites.",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Har Ki Pauri Ganga Aarti",
      "Day 2: Mansa Devi & Chandi Devi Temple",
      "Day 3: Rishikesh Ram Jhula & Laxman Jhula",
      "Day 4: Yoga & Adventure Activities",
      "Day 5: Departure",
    ],
    image: abc5,
  },
  {
    id: 106,
    name: "Kedarnath Yatra",
    duration: "6 Days / 5 Nights",
    price: 12999,
    catagory: "Holy",
    location: "Kedarnath, Uttarakhand",
    description:
      "An ancient riverside pilgrimage town with a chain of nearly 100 Shiva temples built along the Yamuna riverbank. It is believed to be a place blessed by Lord Shiva himself and attracts devotees during Shivratri fairs.",
    services: ["Transport", "Accommodation", "Food", "Guide", "Pony Service"],
    itinerary: [
      "Day 1: Haridwar Arrival",
      "Day 2: Guptkashi Stay",
      "Day 3: Kedarnath Trek & Darshan",
      "Day 4: Kedarnath Temple Morning Aarti",
      "Day 5: Return to Guptkashi",
      "Day 6: Departure",
    ],
    image: abc3,
  },
  {
    id: 721,
    name: "Naimisharanya (Sitapur) ",
    duration: "5 Days / 4 Nights",
    price: 11999,
    catagory: "Holy",
    location: "Badrinath, Uttarakhand",
    description:
      "A sacred forest mentioned in the Mahabharata and Puranas. It is believed that Lord Vishnu destroyed demons here. Chakra Tirth, Lalita Devi Temple, and Hanuman Gaddi are the prime attractions. It is a serene place for meditation and spiritual exploration.",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Haridwar Arrival",
      "Day 2: Joshimath Stay",
      "Day 3: Badrinath Darshan",
      "Day 4: Mana Village Visit",
      "Day 5: Departure",
    ],
    image: abc2,
  },
  {
    id: 823,
    name: "Dwarka-Somnath Tour",
    duration: "4 Days / 3 Nights",
    price: 8999,
    catagory: "Holy",
    location: "Dwarka & Somnath, Gujarat",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Dwarkadhish Temple",
      "Day 2: Nageshwar Jyotirlinga",
      "Day 3: Somnath Temple",
      "Day 4: Departure",
    ],
    image: abc5,
  },
  {
    id: 132,
    name: "Dudhwa National Park (Lakhimpur Kheri): ",
    duration: "4 Days / 3 Nights",
    price: 8999,
    catagory: "Holy",
    description:
      "A part of Project Tiger, Dudhwa is home to Bengal tigers, leopards, swamp deer, rhinos, and migratory birds. Jeep safaris, birdwatching, and elephant rides make it a thrilling experience for wildlife lovers.",
    location: "Dwarka & Somnath, Gujarat",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Dwarkadhish Temple",
      "Day 2: Nageshwar Jyotirlinga",
      "Day 3: Somnath Temple",
      "Day 4: Departure",
    ],
    image: abc5,
  },

  {
    id: 1345,
    name: "Katarniaghat Wildlife Sanctuary (Bahraich) ",
    duration: "4 Days / 3 Nights",
    price: 8999,
    catagory: "Holy",
    description:
      "This sanctuary is rich in biodiversity with gharials, Gangetic dolphins, elephants, and rare bird species. It offers eco-tourism experiences with river boating and forest exploration.",
    location: "Dwarka & Somnath, Gujarat",
    services: ["Transport", "Accommodation", "Food", "Guide"],
    itinerary: [
      "Day 1: Dwarkadhish Temple",
      "Day 2: Nageshwar Jyotirlinga",
      "Day 3: Somnath Temple",
      "Day 4: Departure",
    ],
    image: abc5,
  },
];
